<?php

namespace AppBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends DocumentRepository
{
    public function count()
    {
        $qb = $this->getDocumentManager()->createQueryBuilder('AppBundle:Task');

        return $qb->getQuery()->count();
    }

    public function getUserTasks($user)
    {
        $qb = $this->getDocumentManager()->createQueryBuilder('AppBundle:Task');

        return $qb->all(['userId' => $user]);
    }

    public function getLastTask($user)
    {
        $qb = $this->getDocumentManager()->createQueryBuilder('AppBundle:Task');
        $qb->field('userId')->equals($user->getUsername())->sort(['itemId' => -1]);

        return $qb->getQuery()->getSingleResult();
    }
}
